CREATE FUNCTION [dbo].[FN_MiladiToShamsi] (@D DATETIME)
RETURNS char(10)
AS  
BEGIN 
  DECLARE @ADAY INT
  DECLARE @AMONTH INT
  DECLARE @AYEAR  INT
  DECLARE @VALUE INT 
  DECLARE @A1 VARCHAR(10)
  DECLARE @B1 VARCHAR(10)
  DECLARE @C1 VARCHAR(10)
  DECLARE @TDAY INT
  DECLARE @TMONTH INT
  DECLARE @TYEAR INT
  DECLARE @T_TEMP INT
  DECLARE @CABISEHYEAR INT
  DECLARE @TMONTHEND INT
  DECLARE @NUMDAYS DECIMAL
  DECLARE @NEW_DAY DateTIME
  DECLARE @A DateTIME
  DECLARE @OUTPUT char(10)
  DECLARE @OUTPUT_INT char(10)
  SET @NUMDAYS = DATEDIFF( D,'1921/3/21',@D)
  SET @ADAY=1
  SET @AMONTH=1
  SET @AYEAR=1300
  SET @CABISEHYEAR = @NUMDAYS / 1461
  SET @NUMDAYS = @NUMDAYS -  @CABISEHYEAR *1461
  SET @TYEAR= @NUMDAYS / 365

  IF @Tyear = 4 
        BEGIN
         SET   @Tyear = @Tyear - 1
        END
  SET @NUMDAYS = @NUMDAYS - @TYEAR *  365 
  SET  @TMONTH = @NUMDAYS  / 31
  IF   @TMONTH > 6
      BEGIN
        SET @TMONTH = 6  
      END      
  SET @NUMDAYS = @NUMDAYS - @TMONTH * 31
  SET @TMONTHEND = 0
  IF @NUMDAYS >= 30 AND @TMONTH = 6
      BEGIN
           SET @TMONTHEND = @NUMDAYS  / 30 
           IF @TMONTHEND >= 5 
                   BEGIN
                         SET  @TMONTHEND =5
                   END    /*   IF  44*/
           SET @NUMDAYS = @NUMDAYS - @TMONTHEND  * 30 
      END  /*    IF   41*/
  SET @TMONTH = @TMONTH  + @TMONTHEND
  SET @TDAY =   @NUMDAYS
  SET @TYEAR = @TYEAR + @CABISEHYEAR *4
  SET @AYEAR = @AYEAR + @TYEAR
  SET @AMONTH = @AMONTH + @TMONTH
  SET @ADAY = @ADAY + @TDAY
  SET @A1= CONVERT(varchar(4), @AYEAR,3)
  SET @B1 = CONVERT(varchar(2), @AMONTH,3)
  SET @C1 = CONVERT(varchar(2), @ADAY,3)
  IF LEN(@B1) = 1
      BEGIN
      SET @B1 = '0' + @B1
      END
  IF LEN(@C1) = 1
      BEGIN
      SET @C1 = '0' + @C1
      END
  SET  @OUTPUT =  @A1+'/'+@B1+'/'+@C1
  SET @OUTPUT_INT =@OUTPUT
 -- SET @OUTPUT_INT = @OUTPUT_INT - 13000000
 if(convert(char(10),CONVERT(date,GETDATE())) ='2021-03-20')
 begin
   set @OUTPUT_INT='1399/12/30'
 end
  RETURN @OUTPUT_INT
END

--result = 1400/08/26